version: "3.6"

services:
  postgres:
    build: ./docker
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: aonn
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      postgres:


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
